---
- name: Wait for VMs to start
  wait_for_connection:

- name: Add singning keys for a group
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Add repos for a group
  apt_repository:
    repo: deb https://nginx.org/packages/ubuntu/ jammy nginx
    state: present

- name: Install Nginx
  apt:
    name: nginx=1.24.0-1~jammy
    state: present

- name: Render config file
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Enable services group
  service:
    name: nginx
    state: started
    enabled: yes

- name: Install UFW
  apt:
    name: ufw
    state: present

- name: Enable UFW on start
  service:
    name: ufw
    state: started
    enabled: yes

- name: Deny everything and enable UFW
  ufw:
    state: enabled
    policy: deny

- name: Set logging
  ufw:
    logging: 'on'

- name: Allow all access to tcp port 22
  ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow all access to tcp port 80
  ufw:
    rule: allow
    port: '80'
    proto: tcp
