---

- name: Wait for VMs to start
  wait_for_connection:

- name: Add singning keys for a group
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-7.0.asc
    state: present

- name: Add repos for a group
  apt_repository:
    repo: deb http://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse
    state: present

- name: Install MongoDB
  apt:
    name: mongodb-org #=4.4.6
    state: present
  notify:
    - restart mongo

- name: Copy MongoDB config
  copy:
    src: mongod.conf
    dest: /etc/mongod.conf
  notify:
    - restart mongo

- name: mongoDB - Ensure that service is started and enabled
  service:
    name: mongod.service
    state: started
    enabled: yes

- name: Add singning keys for a group
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add repos for a group
  apt_repository:
    repo: deb https://deb.nodesource.com/node_16.x jammy main
    state: present

- name: Install NodeJS
  apt:
    name: nodejs
    state: present

- name: Install pm2
  npm:
    name: pm2
    global: yes

- name: Creates APP directory
  file:
    path: ~/app
    state: directory

- name: Deploy app
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: '../../app-db/app.js', dest: '~/app/app.js' }
    - { src: '../../app-db/db.js', dest: '~/app/app.js' }
    - { src: '../../app-db/package.json', dest: '~/app/package.json' }
    - { src: '../../app-db/package-lock.json', dest: '~/app/package-lock.json' }
  notify:
    - build app
    - stop pm2
    - start pm2
